FROM node:20-alpine AS base

WORKDIR /server

COPY package*.json ./

RUN npm ci --only=production

EXPOSE 3000

COPY . .

RUN npm run build

FROM node:20-alpine AS runtime

WORKDIR /server

COPY --from=base /server .

CMD ["node", "dist/main.js"]
